name: LLM Prompt Evaluation

on:
  pull_request:
    paths:
      - 'src/github_actions/**'
  workflow_dispatch:

env:
  TARGET_DIR: src/github_actions

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Cache promptfoo data
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/promptfoo
          key: ${{ runner.os }}-promptfoo-${{ hashFiles('${{ env.TARGET_DIR }}/**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-promptfoo-

      - name: Run promptfoo evaluation
        uses: promptfoo/promptfoo-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompts: '${{ env.TARGET_DIR }}/**/*.json'
          config: '${{ env.TARGET_DIR }}/promptfooconfig.yaml'
          cache-path: ~/.cache/promptfoo
