name: LLM Prompt Evaluation

on:
  pull_request:
    paths:
      - 'src/github_actions/**'
  workflow_dispatch:

env:
  TARGET_DIR: src/github_actions

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache promptfoo data
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/promptfoo
          key: ${{ runner.os }}-promptfoo-${{ hashFiles('${{ env.TARGET_DIR }}/**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-promptfoo-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up promptfoo
        run: npm install -g promptfoo

      - name: Run promptfoo evaluation
        id: eval
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPTFOO_CACHE_PATH: ~/.cache/promptfoo
        run: promptfoo eval -o output.json --share
        working-directory: ./${{ env.TARGET_DIR }}

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = JSON.parse(fs.readFileSync('./output.json', 'utf8'));
            const body = `⚠️ LLM prompt was modified.\n\n| Success | Failure |\n|---------|---------|\n| ${output.results.stats.successes}      | ${output.results.stats.failures}       |\n\n**» [View eval results](${output.shareableUrl}) «**`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
        working-directory: ./${{ env.TARGET_DIR }}
